### ISSUE TITLE
Unable to update to 1.13.1 from 1.12.0 - getting build error

### ISSUE THREAD

**Issue by Manav-Seth** [timheuer/alexa-skills-dotnet#197]
Hello, I am currently on 1.12.0 of Alexa.Net in my .net core web app. I was trying to update to 1.13.1 as that is the latest nuget package available but I am getting this error which I am unable to figure out.

In the controller constructor, I am currently doing this: (since my web app is trying to sync updates to Alexa shopping list into another app which I use to track shopping list).

_RequestConverter.RequestConverters.Add(new ListSkillEventRequestTypeConverter());_

This is working fine on 1.12.0 but on 1.31.1,  I am getting the following build errors:

The type 'IRequestTypeConverter' is defined in an assembly that is not referenced. You must add a reference to assembly 'Alexa.NET, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. (CS0012)
Error CS1503: Argument 1: cannot convert from 'Alexa.NET.ListSkillEventRequestTypeConverter' to 'Alexa.NET.Request.Type.IRequestTypeConverter' (CS1503)

And then I am getting the following additional errors as well on the following line (again, working fine on 1.12.0):

var listItemCreatedRequest = input.Request as ListSkillItemCreatedRequest;

Build errors: 
Error CS0012: The type 'Request' is defined in an assembly that is not referenced. You must add a reference to assembly 'Alexa.NET, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. (CS0012)
Error CS0039: Cannot convert type 'Alexa.NET.Request.Type.Request' to 'Alexa.NET.ListManagement.SkillEvents.ListSkillItemCreatedRequest' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion (CS0039)

Any ideas? Thanks!

**Comment by stoiveyp** [comment]
@timheuer This type is from one of my extensions. Would there be a problem with strong naming the NuGet package and then using an extension that references a package without a strong name (i.e. any of them)

The day is just starting here, I'll try and test another one when I've got to a laptop

**Comment by stoiveyp** [comment]
Yeah I've just confirmed I get the same problem trying to use the Alexa.NET.RequestHandlers package and the Alexa.NET.APL package.

V1.13.0 works without a problem - the strong naming in v1.13.1 breaks the extensions as it starts using a strong naming reference looking for the specific versions of Alexa.NET they were built with and it doesn't match.

@timheuer I'd ask if you could unlist 1.13.1 to stop our users getting broken builds - at the very least it's not a patch change if this is the impact. Then we can discuss next steps if we want to maintain a strong named version of the assembly?

**Comment by timheuer** [comment]
Grr I hate this. I unlisted this. I talked with the runtime team and this shouldn’t have been the case. Every time I have a convo about strong naming it bites me. 

1.13.1 is unlisted.

**Comment by stoiveyp** [comment]
Thank you - sorry for the disruption.

Interestingly although I got the problem with a .NET Core lambda (trying both VS and dotnet CLI) I tried my management UWP app over lunch and didn't get the same problem (didn't go too far but it at least built)

Been so long since I've worried about strong naming I wouldn't know how the assembly references are treated with such different targets - but worthy of note at least.

If there is anything I can do with the extensions to attempt to move the issue forward I'm happy to try

**Comment by NickEricson** [comment]
On a "keep breaking things until they work" note... it would be nice to have signed extension assemblies as well. I've seen some projects release a XYZ.Signed version of their packages to handle the build issues.

**Comment by timheuer** [comment]
@NickEricson is your app using this in a .NET Framework scenario or .NET core?

**Comment by NickEricson** [comment]
.Net Framework (we target 462 now). We do some cross compile to .Net core also but don't need that right away.

**Comment by timheuer** [comment]
Okay, got it.  Well strong-naming is indeed a breaking aspect for .NET Framework, but isn't for .NET Core.  Unfortunately the compiler still doesn't know yet about 'not for .NET core' part of it so even thought it isn't breaking the runtime it is during build.  I'm going to have to re-think this and rollback strongnaming as we have a lot of devs that use the extensions.  Unless @stoiveyp will change as well (which then could have further downstream) we'll ahve to think of a way to safely do this.

**Comment by stoiveyp** [comment]
I'm able to look at strong naming some of the extensions. Certain ones (like management) just couldn't because they rely on other 3rd party assemblies that aren't.

My concern is that if I do that for this version, doesn't that mean they all break again when we release the next one with a similar version mismatch to what we have now? I'd be artificially bumping them all every time the main library changed version - developers would have to keep everything in step to work properly and we'd be complicating the majority of implementations.

Looking around the problem I've seen several .StrongNamed suffix assemblies for those that need it (not many still supported, but still). If the main library did that I could work with getting a similar convention sorted for the extensions - developers have a choice at least and the majority stay with NuGet working as expected.

**Comment by NickEricson** [comment]
Just to let you know we don't need the strong named version anymore. Other's may but want to be sure you don't continue to make changes just for us.

**Comment by timheuer** [comment]
Thanks for the comment @NickEricson -- curious why it isn't needed anymore?  Not using the lib? fork? other reasons...just curious.

**Comment by NickEricson** [comment]
We can Authenticode sign it instead (which is much more reasonable).

We are using the Alexa.Net packages now both in a public nuget package and in our service.
github/nuget: https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop (the Alexa adapter)
service: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-alexa?view=azure-bot-service-4.0

Thanks for the great package.

**Comment by timheuer** [comment]
Great, thanks for the update!  And for the compliments to the team here delivering the full package!
